### ISSUE TITLE
Adjust dependabot configuration

### ISSUE THREAD

**Issue by jessicamcinchak** [theopensystemslab/map#190]
Since introducing a test step to our CI, it seems like most dependabot pull requests will now fail when opened. If you checkout the branch, run `pnpm i`, and commit the updated pnpm-lock.yml file, then the tests succeed. 

PNPM isn't officially supported by dependabot yet, which is why it only updates package.json and not the lockfile. See https://github.com/dependabot/dependabot-core/issues/1736

Should investigate if there's a tweak we can make to our existing workflow commands (eg drop `--no-frozen-lockfile` flag?) or if we should consider implementing one of the dependabot/pnpm work-arounds like a custom Github Action described in the thread above.

Additionally would be nice to bundle our dependabot PRs for less frequent notifications.

**Comment by DafyddLlyr** [comment]
Resolved in https://github.com/theopensystemslab/map/pull/319 🏅
