### ISSUE TITLE
Add different examples

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/map#26]
Related https://github.com/theopensystemslab/map/pull/25

**Comment by jessicamcinchak** [comment]
a few recent ideas around this:

non-storybook:
- https://component.kitchen/blog/posts/building-a-storybook-like-demo-browser-with-web-components-a-much-simpler-way-to-get-most-of-the-benefits
- https://pitsby.com/
- https://dev.to/webpadawan/api-viewer-document-your-web-components-api-p8j

storybook:
- build with vite? https://storybook.js.org/blog/storybook-for-vite/
