### ISSUE TITLE
Is it possible to make Open Layers methods available on the web component? 

### ISSUE THREAD

**Issue by jessicamcinchak** [theopensystemslab/map#39]
A question from BOPS in the context of resizing the map: is it possible to do something like...
```js
const map = document.querySelector("my-map");
map.olmap.someOpenLayersMethod();
```

The event listener approach is working, but curious is this is possible as an alternative. Need to read more into Lit docs here

**Comment by peterszerzo** [comment]
This is probably way too late, but if the behavior of native custom elements is of any indication, this code:

```ts
customElements.define("my-component", class extends HTMLElement {
  /* other custom element stuff */
  someMethod() {
    this.something.callMethod();
  }
});
```

will expose `document.querySelector("my-component").someMethod();` to the outside with the correct context. I suppose this is the custom version of the usual `document.querySelector("input").focus();`.
